<?php
namespace app\admin\controller;

use app\common\controller\AdminBase;
use think\Db;

class Member extends AdminBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function authentication()
    {
        $list = Db::name('user')->order('id desc')->paginate(10);

//        $this->assign('list',$list);
        return $this->fetch('authentication',['list' => $list]);
    }
    public function ajaxReturn($data = [],$type = 'json'){
        header('Content-Type:application/json; charset=utf-8');
        $data = !empty($data) ? $data : ['status' => 1, 'msg' => '操作成功'];
        exit(json_encode($data,JSON_UNESCAPED_UNICODE));
    }
    public function check($id)
    {
        $value = Db::name('user')->where('id',$id)->value('flag');

        if($value == 0){
            Db::name('user')->where('id',$id)->update(['flag' => 1]);
//            $this->ajaxReturn(array('code'=>200, 'msg'=>'审核通过'));
            $data = array('code'=>200, 'msg'=>'审核通过');
//            return json_encode($data,1);
            $this->ajaxReturn($data);
        }elseif($value ==1){
            $data = array('code'=>0, 'msg'=>'已经审核通过了');
//            return json_encode($data,1);
            $this->ajaxReturn($data);
        }

    }
}